import "./globals.css";
import SideBar from "@/components/sidebar";
import RightsideBar from "@/components/rightsideBar";
import GoTopComponent from "@/components/goTop";
import Search from "@/components/Search/page";
import Advertise from "@/components/advertise";

export const metadata = {
  title: "Feed Your Hunger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoTopComponent />
        <div className={"main-container"}>
          <SideBar />
          <div className={"main-wrapper"}>
            <Search />
            <Advertise />
            {children}
          </div>
          <RightsideBar />
        </div>
      </body>
    </html>
  );
}
