
import './globals.css'
import SideBar from "@/components/sidebar";
import RightsideBar from "@/components/rightsideBar";


export const metadata = {
  title: 'Feed Your Hunger',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <div className={'main-container'}>
        <SideBar/>
        <div className={'main-wrapper'}>
          {children}
        </div>
        <RightsideBar/>
      </div>
    </body>
    </html>
  )
}
