
import './globals.css'
import SideBar from "@/components/sidebar";


export const metadata = {
  title: 'Feed Your Hunger',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <div className={'main-container'}>
        <SideBar/>
        {children}
      </div>
    </body>
    </html>
  )
}
